"""add current attack phase

Revision ID: eb2f186f1fdc
Revises: 2b58840b3900
Create Date: 2025-08-04 12:22:58.940588

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "eb2f186f1fdc"
down_revision = "2b58840b3900"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_attack_phase",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("phase", sa.String(length=64), nullable=False),
        sa.Column("chain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["attack_chain.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_current_attack_phase_chain_id"),
        "current_attack_phase",
        ["chain_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_current_attack_phase_chain_id"), table_name="current_attack_phase"
    )
    op.drop_table("current_attack_phase")
    # ### end Alembic commands ###
