"""fix agent

Revision ID: 2ed96921ea3b
Revises: eb2f186f1fdc
Create Date: 2025-08-23 17:24:58.697263

"""


from alembic import op

# revision identifiers, used by Alembic.
revision = "2ed96921ea3b"
down_revision = "eb2f186f1fdc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("agent_agent_name_key"), "agent", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("agent_agent_name_key"),
        "agent",
        ["agent_name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
