"""fix types

Revision ID: b4d2c51dc55a
Revises: 2ed96921ea3b
Create Date: 2026-09-03 17:30:38.180302

"""

# revision identifiers, used by Alembic.
revision = "b4d2c51dc55a"
down_revision = "2ed96921ea3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
