name: CI-React

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/oxc-frontend-ci.yml"

  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/oxc-frontend-ci.yml"

permissions: {}

jobs:
  oxc-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies by lock
        run: bun install --frozen-lockfile
      # style somewhere close to Google JS Style Guide 
      - name: Check formatting by oxfmt
        run: bun run format:check

      - name: Lint by oxlint
        run: bun run lint

      - name: Build errors check
        run: bun run build
