name: semgrep_frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

  pull_request:
    paths:
      - "frontend/**"

permissions:
  # informational
  contents: read

jobs:
  semgrep_react:
    runs-on: ubuntu-latest
    # cuz many fp
    continue-on-error: true

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # https://semgrep.dev/p/javascript
      - name: Run Semgrep Analysis
        run: semgrep scan --config p/javascript --metrics=off frontend/