name: semgrep_frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

  pull_request:
    paths:
      - "frontend/**"

permissions:
  # informational
  contents: read

jobs:
  semgrep_react:
    runs-on: ubuntu-latest
    # cuz many fp
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # https://semgrep.dev/docs/getting-started/quickstart
      - name: Run Semgrep Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          # https://semgrep.dev/p/javascript
          config: p/javascript
          extra_args: --metrics=off frontend/
