name: semgrep_backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

  pull_request:
    paths:
      - "backend/**"

permissions:
  # informational
  contents: read

jobs:
  semgrep_fastapi:
    runs-on: ubuntu-latest
    # cuz many fp
    continue-on-error: true

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # https://semgrep.dev/p/python
      - name: Run Semgrep Analysis
        run: semgrep scan --config p/python --metrics=off backend/